### ISSUE TITLE
How to adjust tracker distance?

### ISSUE THREAD

**Issue by Mezfik** [derl30n/esx_pursuit_helper#3]
Any please help me to adjust tracker distance ? The tracker gets disconnected when its goes short distance.

**Comment by MisterChocker** [comment]
The tracker currently does not work in MP due to syncing issues.

**Comment by Mezfik** [comment]
MP?

**Comment by Mezfik** [comment]
Can you please provide any other good trackers?

**Comment by Mezfik** [comment]
@MisterChocker

**Comment by MisterChocker** [comment]
> MP?

Multiplayer

> Can you please provide any other good trackers?

Unfortunately I can't.

**Comment by Tinky124** [comment]
@MisterChocker any new updates ? :( its very good script but gps doesnt sycn with players #2 
maybe
`SetBlipAsMissionCreatorBlip(gps, true)` will help?

**Comment by MisterChocker** [comment]
> @MisterChocker any new updates ? :( its very good script but gps doesnt sycn with players #2
> maybe
> `SetBlipAsMissionCreatorBlip(gps, true)` will help?

@Tinky124 It may help, unfortunately I am currently lacking the time to do anything.

But feel free to try it yourself, I'd appreciate a feedback if you do so.

**Comment by Mezfik** [comment]
@Tinky124 Do you know how to adjust its distance?

**Comment by MisterChocker** [comment]
> @Tinky124 Do you know how to adjust its distance?

The distance of my tracker is(/should be) infinite.

**Comment by Mezfik** [comment]
@MisterChocker But my tracker gets disconnected at 0.2 mile?

**Comment by MisterChocker** [comment]
@Mezfik are you sure you are using the correct tracker? I just checked and it still works as described.

**Comment by Tinky124** [comment]
@Mezfik Beacuse you use Onesync Infinity.

**Comment by MisterChocker** [comment]
> @Mezfik Beacuse you use Onesync Infinity.

Yes thats correct.

**Comment by Mezfik** [comment]
@MisterChocker @Tinky124 Yeah i am using your tracker. We are not using onesync and it gets disconnected at 0.5 mile now.

**Comment by MisterChocker** [comment]
@Mezfik my tracker is not restricted to any (render) distance.
Try reinstall the plugin and follow the instruction step by step.

**Comment by Mezfik** [comment]
@MisterChocker What do you mean by plugin bro?

**Comment by MisterChocker** [comment]
@Mezfik Re-download and re-install to ensure you are using the correct version..
Use this link https://github.com/MisterChocker/esx_pursuit_helper/archive/refs/tags/v2.zip

**Comment by marvelbro** [comment]
@Mezfik @MisterChocker @Tinky124
We are also facing the same issue, earlier this tracker is working fine and perfect, but last month started facing this issue, tracker losing after 0.51 miles and notification is coming siganal lost, Checked with few other servers also they are also facing the same issue, pleae let us know some one can able to help on this

**Comment by Mezfik** [comment]
@MisterChocker Yeah I have downloaded the same thing.
